### ISSUE TITLE
File names generated in cam.py

### ISSUE THREAD

**Issue by Earth13wells** [Earth13wells/Methane#1]
Current file output:
     1  image0.jpg
     2  image10.jpg
     3  image11.jpg
     4  image1.jpg
     5  image2.jpg
     6  image3.jpg
     7  image4.jpg
     8  image5.jpg
     9  image6.jpg
    10  image7.jpg
    11  image8.jpg
    12  image9.jpg
Desired Outcome:
     1  image000.jpg
     2  image001.jpg
     3  image002.jpg
     4  image003.jpg
     5  image004.jpg
     6  image005.jpg
     7  image006.jpg
     8  image007.jpg
     9  image008.jpg
    10  image009.jpg
    11  image0010.jpg
    12  image0011.jpg

**Comment by Dugchugy** [comment]
fixed by adding time to file output
